name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  APP_ENV: "ci"

jobs:
  format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-compose-action@v2
      - run: docker compose up --build -d
      - run: docker compose exec app npm run test
      - run: docker compose down

  coverage:
    name: Run Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-compose-action@v2
      - run: docker compose up --build -d
      - run: docker compose exec app npm run coverage
      - run: docker compose down
